version: '3.4'

services:
  server:
    image: seker212/et_server:pro
    ports:
      - "30443:443"
    environment:
      - ASPNETCORE_HTTPS_PORT=30443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=a
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - CONNECTION_STRING=Server = database; Port = 5432; Database = postgres; User Id = banan; Password = s9n5#@Jo;
    volumes:
      - ~/https:/https:ro
  
  database:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=s9n5#@Jo"
      - "POSTGRES_USER=banan"
